// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmyER6TNPQrBGZ1kT2posEH3jS52uGlb8',
    appId: '1:437172282524:web:06c0aa24a387f7fe8b7959',
    messagingSenderId: '437172282524',
    projectId: 'shop-cat-eb9d3',
    authDomain: 'shop-cat-eb9d3.firebaseapp.com',
    storageBucket: 'shop-cat-eb9d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT24ig8DHD_ONpO1STs91NoiS1ZqUdGjE',
    appId: '1:437172282524:android:bcfffa64fab985558b7959',
    messagingSenderId: '437172282524',
    projectId: 'shop-cat-eb9d3',
    storageBucket: 'shop-cat-eb9d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoqzWFwvW5I28kG_POlSUzgYNZaiSqdqM',
    appId: '1:437172282524:ios:9dfb6fc8fb33587c8b7959',
    messagingSenderId: '437172282524',
    projectId: 'shop-cat-eb9d3',
    storageBucket: 'shop-cat-eb9d3.appspot.com',
    iosBundleId: 'com.example.finalMobile',
  );
}
